// Seeder for genders table - genders.seeder.ts
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const studios = [
  "8bit",
  "81 Produce",
  "10Gauge",
  "8PAN",
  "7doc",
  "5 Inc.",
  "1IN",
  "33 Collective",
  "AIC",
  "A-1 Pictures",
  "AQUA ARIS",
  "Ashi Productions",
  "Actas",
  "Asahi Production",
  "Artland",
  "A.C.G.T.",
  "AIC ASTA",
  "Artmic",
  "Alpha Animation",
  "AIC PLUS+",
  "AT-2",
  "Ascension",
  "Ascendent Animation",
  "AXsiZ",
  "Asura Film",
  "AIC Build",
  "arma bianca",
  "Arvo Animation",
  "A-Line",
  "AIC Classic",
  "A-Real",
  "ACC Production",
  "ARCUS",
  "ABC Frontier",
  "Animation Staff Room",
  "Anon Pictures",
  "Anpro",
  "Au Praxinoscope",
  "Anima&Co.",
  "AtelierPontdarc",
  "AC-Bu",
  "AIC RIGHTS",
  "Acca effe",
  "ARECT",
  "Arch",
  "Adonero",
  "Ai Yume Mai",
  "Aiti St.",
  "Alfred Imageworks",
  "Alice Production",
  "Arcturus",
  "An DerCen",
  "Andraft",
  "Alke",
  "Anime Tokyo",
  "Aurora Animation",
  "Animation 501",
  "AIC Project",
  "ANiMix Project",
  "Atti Production",
  "Atorie A.B.C.",
  "AION Studio",
  "Amineworks",
  "Amarcord",
  "Aiko",
  "Animation Lab Japan",
  "Ai Si Animation Studio",
  "Ark",
  "Albacrow",
  "Anime Friend",
  "ANIDO FILM",
  "Ankama Animations",
  "Aurum Production",
  "Arcs Create",
  "AIC Takarazuka",
  "bilibili",
  "Bandai Entertainment",
  "Brain's Base",
  "BS Fuji",
  "Bandai Namco Pictures",
  "BS NTV",
  "Bandai Namco Music Live",
  "Blue bread",
  "Bridge",
  "B.CMAY PICTURES",
  "Bandai Visual USA",
  "Big Firebird Culture",
  "Bouncy",
  "Blade",
  "Bibury Animation Studios",
  "BYMENT",
  "Blue Cat",
  "BOMB! CUTE! BOMB!",
  "Bakken Record",
  "BS TV Tokyo",
  "Boyan Pictures",
  "B&T",
  "Bebow",
  "BUG FILMS",
  "Big Wing",
  "Bibury Animation CG",
  "Buemon",
  "Blaze Studio",
  "Big Pine Animation Studio",
  "Bigcat Studio",
  "Blue Moon Studio Inc.",
  "Blue Note",
  "Borutong",
  "Benlai Pictures",
  "Brio Animation",
  "Beijing Sunchime Happy Culture Company",
  "Bitgang",
  "Bianyue Culture",
  "Beijing Rocen Digital",
  "Creators in Pack",
  "C2C",
  "C-Station",
  "Collaboration Works",
  "CygamesPictures",
  "Craftar Studios",
  "CHOCOLATE",
  "CLAP",
  "Creative Power Entertaining",
  "Comma Studio",
  "Chiptune",
  "Coastline Animation Studio",
  "Cloud Hearts",
  "CUCURI",
  "CANON RECORDINGS",
  "Cafe de Jeilhouse",
  "Creators Dot Com",
  "CMC Media",
  "China South Angel",
  "CD Projekt Red",
  "Cutie Bee",
  "Circle Tribute",
  "Circus Production",
  "C&S Production",
  "C and R",
  "Concept Films",
  "Congzhuo Animation",
  "CinePix",
  "Chimu Jika Hatsuden",
  "Discotek Media",
  "DLE",
  "Diomedéa",
  "David Production",
  "Disney Platform Distribution",
  "DMM.futureworks",
  "Dongwoo A&E",
  "Decovocal",
  "DandeLion Animation Studio",
  "Dream Entertainment",
  "Drive",
  "Daewon Media",
  "Dangun Pictures",
  "DR Movie",
  "DiC Entertainment",
  "Datama Film",
  "Dancing CG Studio",
  "Digital Network Animation",
  "D.ROCK-ART",
  "Dazzling Star",
  "drop",
  "Dyna Method",
  "Djinn Power",
  "Dongyang Animation",
  "Dai-Ichi Douga",
  "Daysview Animation",
  "Delpic",
  "Days",
  "Drawing and Manual",
  "Dawn Animation",
  "Da Huoniao Donghua",
  "Eiken",
  "EMT Squared",
  "Echoes",
  "E&G Films",
  "Encourage Films",
  "EDGE",
  "Enishiya",
  "Emon",
  "Eallin",
  "East Fish Studio",
  "E&H Production",
  "EKACHI EPILKA",
  "Egg",
  "Enjin Productions",
  "Ezόla",
  "Executive Decision",
  "Eshoya Honpo",
  "EOTA",
  "evg",
  "Enzo Animation",
  "Ekakiya",
  "Ether Kitten",
  "Ekura Animal",
  "Ezo Kobo",
  "feel.",
  "Fanworks",
  "Foch Films",
  "Flat Studio",
  "Flavors Soft",
  "Fuji Creative",
  "Felix Film",
  "Front Line",
  "Fever Creations",
  "Fugaku",
  "flag Co.",
  "FUNNY MOVIE",
  "Geneon Entertainment USA",
  "Gonzo",
  "Geneon Universal Entertainment",
  "Geidai Animation",
  "Gainax",
  "Gathering",
  "Green Bunny",
  "GoHands",
  "GANSIS",
  "Good Smile Film",
  "Gaina",
  "Garden Culture",
  "G-angle",
  "Grouper Productions",
  "Geno Studio",
  "G-Lam",
  "Gravity Well",
  "Gekkou",
  "GIFTanimation",
  "GARDEN LODGE",
  "G.P Entertainment",
  "Giga Production",
  "Gainax Kyoto",
  "GRIZZLY",
  "Garyuu Studio",
  "Gambit",
  "Green Monster Team",
  "Guton Animation Studio",
  "GUMBLAB",
  "Griot Groove",
  "Gunners",
  "Gonzino",
  "GA-CREW",
  "GAV Video",
  "Gosay Studio",
  "Grom",
  "Hololive Production",
  "Haoliners Animation League",
  "Hoods Entertainment",
  "High Energy Studio",
  "Happinet Phantom Studios",
  "Horgos Coloroom Pictures Co., Ltd.",
  "Horannabi",
  "Hand to Mouse.",
  "Husio Studio",
  "HS Pictures Studio",
  "Hayabusa Film",
  "Hu Po Donghua",
  "Hiroshima City University",
  "Hifumi Shobo",
  "HM Heros",
  "happyproject",
  "Hai An Xian Donghua Gongzuo Shi",
  "helo.inc",
  "Hanjin Animation",
  "iQIYI",
  "ILCA",
  "Imagin",
  "IMAGICA Lab.",
  "Imagineer",
  "I.Gzwei",
  "Image House",
  "Iconix Entertainment",
  "Issen",
  "Imagica Infos",
  "Inugoya",
  "iDRAGONS Creative Studio",
  "Imagestone Inc.",
  "iDreamSky",
  "Infinity Vision",
  "Imagica Digitalscape",
  "Ishibashi Planning",
  "IKK Room",
  "Irawias",
  "Imagica Imageworks",
  "Ishimori Entertainment",
  "Jumondo",
  "J.T.P.P.",
  "Jumonji",
  "JCF",
  "Joker Films",
  "J.C.F.",
  "Japan Taps",
  "J.K.I",
  "JOF",
  "Jichitai Anime",
  "JJJOY Animation Studios",
  "Kyoto Animation",
  "Kachidoki Studio",
  "Kinema Citrus",
  "KSS",
  "Kamikaze Douga",
  "Khara",
  "Kuri Jikken Manga Koubou",
  "Kate Arrow",
  "Kitty Film Mitaka Studio",
  "Kanaban Graphics",
  "Konami Cross Media NY",
  "KJJ Animation",
  "Kyoto Broadcasting System",
  "Kung Fu Frog Animation",
  "Kantou Douga Kai",
  "Kill Time Communication",
  "Kobe Design University",
  "Kusama Art",
  "Keica",
  "Kami Kukan",
  "Kuaikan Manhua",
  "Kyushu Network Animation",
  "Kent House",
  "Kigumi",
  "KKC Animation Production",
  "Kaca Entertainment",
  "Karasfilms",
  "Kinematics",
  "LIDENFILMS",
  "Lune-Pictures",
  "Lerche",
  "Lay-duce",
  "L²Studio",
  "LAN Studio",
  "Lapin Track",
  "Light Chaser Animation Studios",
  "Liyu Culture",
  "Liu Cong Animation",
  "LX Animation Studio",
  "l-a-unch・BOX",
  "LB Commerce",
  "Lingsanwu Animation",
  "Live2D Creative Studio",
  "Liber",
  "Locus Corporation",
  "Lead",
  "LEVELS",
  "Lyrics",
  "Mediabank",
  "MAPPA",
  "Mushi Production",
  "Maiden Japan",
  "MediaNet",
  "Millepensee",
  "Mirai Film",
  "Marza Animation Planet",
  "Maho Film",
  "Maxilla",
  "Motion Magic",
  "miHoYoAnime",
  "Making Animation",
  "Meltdown",
  "Mili Pictures",
  "Minakata Laboratory",
  "Maboroshi Koubou",
  "MediaNet Pictures",
  "Mimoid",
  "monofilmo",
  "Micro House",
  "MontBlanc Pictures",
  "MB planning",
  "Melissa",
  "Mousou Senka",
  "Magia Doraglier",
  "Momoi Planning",
  "Manga Productions",
  "MMT Technology",
  "Maro Studio",
  "Moss Design Unit",
  "maroyaka",
  "Miki Production",
  "Mikimoto Production",
  "M&M",
  "MoMo Production",
  "Miyuki Production",
  "MI",
  "Magma Studio",
  "Marone",
  "MAT",
  "MASTER LIGHTS",
  "Mook DLE",
  "Mirai Fusion",
  "Nihon Ad Systems",
  "Nagoya Broadcasting Network",
  "Nomad",
  "Netflix",
  "NichiNare",
  "New Generation",
  "Nice Boat Animation",
  "Nut",
  "Nexus",
  "NHK Art",
  "NADA Holdings",
  "Natural High",
  "New Deer",
  "NANON CREATIVE",
  "Noovo",
  "Namu Animation",
  "Neft Film",
  "Nekonigashi Inc.",
  "nobishiro lab",
  "Network Kouenji Studio",
  "Nippon Ramayana Film Co.",
  "Nishiki Studio",
  "Next",
  "OLM",
  "Office TakeOut",
  "Oddjob",
  "OLM Digital",
  "Onionskin",
  "ORADA COMPANY",
  "Office No. 8",
  "Okuruto Noboru",
  "Office AO",
  "Okumaza",
  "Onion Studio",
  "October Media",
  "Oyster",
  "ONIRO",
  "OZ",
  "ORENDA",
  "Odolttogi",
  "Office DCI",
  "Original Dream",
  "Pierrot",
  "Polygon Pictures",
  "Project No.9",
  "Pony Canyon Enterprises",
  "Pie in the sky",
  "Picture Magic",
  "Production Reed",
  "PRA",
  "PP Project",
  "Peak Hunt",
  "Painting Dream",
  "pH Studio",
  "Platinum Vision",
  "Piso Studio",
  "Pops Inc.",
  "Pollyanna Graphics",
  "Passion Paint Animation",
  "P core",
  "Production D.M.H",
  "Project Team Sarah",
  "production doA",
  "Planet Cartoon",
  "Paper Plane Animation Studio",
  "Point Pictures",
  "Production +h.",
  "Production Wave",
  "Pancake",
  "Polygon Magic",
  "Penta Show Studios",
  "Project Team Muu",
  "Pink Cat",
  "Pak Production",
  "Potato House",
  "Planet Nemo Animation",
  "Poly Animation",
  "Paper Animation",
  "Picona",
  "Piko Studio",
  "Qzil.la",
  "Quad",
  "Qianqi Animation",
  "Qiying Animation",
  "Qualia Animation",
  "Quebico",
  "QualiArts",
  "Ruo Hong Culture",
  "Radix",
  "RG Animation Studios",
  "Red Dog Culture House",
  "Rising Force",
  "Revoroot",
  "Rabbit Machine",
  "Ryuu M's",
  "Ripromo",
  "Ranzai Studio",
  "REALTHING",
  "Reiki Eyes Animation",
  "Studio Deen",
  "Shin-Ei Animation",
  "Shogakukan-Shueisha Productions",
  "SILVER LINK.",
  "Showgate",
  "Satelight",
  "Studio Mausu",
  "Seven",
  "Studio 4°C",
  "Studio Hibari",
  "Studio Comet",
  "Studio 9 Maiami",
  "Sony Music Communications",
  "SANZIGEN",
  "Studio 1st",
  "Sony Pictures Entertainment",
  "Studio Fantasia",
  "Suzuki Mirano",
  "Seven Arcs",
  "Suoyi Technology",
  "Signal.MD",
  "Shirogumi",
  "Studio 3Hz",
  "Studio Kai",
  "Shuka",
  "Science SARU",
  "Saigo no Shudan",
  "Studio Live",
  "Studio Moriken",
  "Studio Hokiboshi",
  "SELFISH",
  "Sola Digital Arts",
  "Sunrise Beyond",
  "Scooter Films",
  "Shion",
  "SMIRAL Animation",
  "Studio Rikka",
  "Silver",
  "Studio Blanc.",
  "Studio Jemi",
  "Studio Crocodile",
  "Studio OX",
  "Shindeban Film",
  "Studio RE:Map",
  "studio MOTHER",
  "Studio Elle",
  "Studio Kaab",
  "Studio Chizu",
  "Shura",
  "Studio Palette",
  "Super Normal Studio",
  "Shochiku Animation Institute",
  "Shimogumi",
  "Shykeumo Animation Studio",
  "Studio Soul",
  "Shinjukuza",
  "Studio Boogie Nights",
  "Studio Guts",
  "Sharefun Studio",
  "S-Wood",
  "Sublimation",
  "Square Enix Visual Works",
  "Shanghai Hippo Animation",
  "Studio M2",
  "Studio Ponoc",
  "Studio Meditation With a Pencil",
  "SIDO LIMITED",
  "Stereotype",
  "studio YOG",
  "Studio Easter",
  "Studio Ranmaru",
  "Staple Entertainment",
  "Stay Luck",
  "Studio Prokion",
  "Sonsan Kikaku",
  "Saetta",
  "Studio Lings",
  "Studio Flad",
  "Studio Ten Carat",
  "Sugar Boy",
  "Sunflowers",
  "Studio Tumble",
  "Shenman Entertainment",
  "Studio Gazelle",
  "Studio Ten",
  "Studio Daisy",
  "Studio Kafka",
  "Studio DURIAN",
  "Suspenders",
  "Studio CANDY BOX",
  "Sony Interactive Entertainment",
  "Samsara Animation Studio",
  "Studio March",
  "Studio Core",
  "Stingray",
  "Sprite Animation Studios",
  "Studio NOIX",
  "Studio Bogey",
  "Sakura Eiga-sha",
  "Studio A. Craft",
  "Square Pictures",
  "Shenfan Animation",
  "Studio Dolphin Night",
  "StarLink",
  "Space-X",
  "Studio Shelter",
  "Studio Ppuri",
  "Studio Mir",
  "Studio UGOKI",
  "Studio AWAKE",
  "Studio Lotus",
  "soket",
  "Sasayuri",
  "Studio Add",
  "Studio N",
  "Studio Fusion",
  "Studio D-Volt",
  "Starlight Entertainment",
  "Studio Himalaya",
  "SANDWICHWORKS",
  "Studio Cats",
  "Studio B&M",
  "Studio Jin",
  "STUDIO6'oN",
  "Sumomo Film",
  "Studio Gadget",
  "studio hb",
  "Story Effect",
  "SJYNEXCUS",
  "Studio W.Baba",
  "Studio Hakk",
  "Studio CA",
  "Studio Khronos",
  "Studio Carbuncle",
  "Studio World",
  "Studio Z5",
  "Studio WHO",
  "Toei Animation",
  "TMS Entertainment",
  "TBS",
  "Tatsunoko Production",
  "Tencent Penguin Pictures",
  "TOHO",
  "TNK",
  "Telecom Animation Film",
  "The Answer Studio",
  "Tamabi",
  "Takun Manga Box",
  "Toranoana",
  "Tsuburaya Productions",
  "TROYCA",
  "Tokyu Agency",
  "Typhoon Graphics",
  "Transcendence Picture",
  "TrioPen Studio",
  "TriF Studio",
  "Thundray",
  "Trash Studio",
  "Tomovies",
  "Teatro Nishi Tokyo Studio",
  "Team YokkyuFuman",
  "Topcraft",
  "Taikong Works",
  "Takahashi Studio",
  "Taomee",
  "Tear Studio",
  "TAKI Corporation",
  "TOHO animation STUDIO",
  "Tokyo Movie",
  "TAP",
  "Tianshi Wenhua",
  "team Yamahitsuji",
  "Tryforce",
  "TthunDer Animation",
  "Tong Ming Xuan",
  "Tonko House",
  "Tomason",
  "Team OneOne",
  "Tonari Animation",
  "Tohjak",
  "TANOsim",
  "Tengu Kobo",
  "The Gate Studio",
  "TanKong Pictures",
  "TypeZero",
  "TV Tokyo Communications",
  "Tsubo Production",
  "Twenty First",
  "TEC",
  "TiMi Studio Group",
  "The Monk Studios",
  "Ten Tails Animation",
  "Team TillDawn",
  "Twilight Studio",
  "Tsukimidou",
  "TOCSIS",
  "ufotable",
  "Ultra Super Pictures",
  "UWAN Pictures",
  "Urban Product",
  "Unend",
  "UchuPeople",
  "Voil",
  "Visual Flight",
  "V-sign",
  "Warner Bros. Japan",
  "Wit Studio",
  "White Fox",
  "WAO World",
  "W-Toon Studio",
  "Wawayu Animation",
  "Wonder Cat Animation",
  "Wong Ping Animation Lab",
  "Wolf Smoke Studio",
  "Wise Guy",
  "Wang Film Productions",
  "Watanabe Promotion",
  "Winfuture Media",
  "Wei Chuang Jiang Xin",
  "Will Palette",
  "Wan Wei Mao Donghua",
  "Xebec",
  "XEBEC M2",
  "Xiaoming Taiji",
  "Xanthus Media",
  "Yomiuri TV Enterprise",
  "Youku",
  "Yokohama Animation Lab",
  "Yaoyorozu",
  "YHKT Entertainment",
  "Yi Chen Animation",
  "Yamiken",
  "yell",
  "Yinhe Changxing Culture",
  "Youth Film Studio",
  "Yili Animation Studio",
  "Yuntu Animation",
  "Zexcs",
  "Zero-G",
  "ZOOM ENTERPRISE"
];

const seed = async () => {
  console.info('Seeding studios 🎬')
  for (let i = 0; i < studios.length; i++) {
    await prisma.studios.upsert({
      where: {
        id: i + 1
      },
      update: {},
      create: {
        name: studios[i]
      },
    })
    console.info(`Studio ${i + 1}/${studios.length} seeded 🏗️`)
  }
  console.info('Studios seeded ✅')
}

export default seed